<?php

/**
 * @file
 * Functions to support theming in the Prometeo2023 theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function prometeo2023_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function prometeo2023_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function prometeo2023_preprocess_node(&$variables) {

}
